# Default values for ups-mon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ups-mon
  tag: test
  pullPolicy: IfNotPresent

liveness:
  initialDelaySeconds: 60
  periodSeconds: 60

config:
  ups:
    name: 
    fullName: 
    location: 

  nut.conf:
    mode: standalone

  ups.conf:
    driver: usbhid-ups
    port: auto
    pollInterval: 15

  upsd.conf:
    listen: "127.0.0.1 3493"
    maxAge: 25

  upsd.users:
    admin:
      name:
      password:
    user:
      name:
      password:

  upsmon.conf:
    notifyCmd: /etc/nut/notifycmd.sh
    deadtime: 25

secrets:
  alert:
    emailTo:
    emailFrom:
    emailFromName:

    smtp:
      host:
      port:
      user:
      password:

    twilio:
      account:
      authToken:
      fromNumber:
      toNumber:

service:
  port: 80
  protocol: TCP
  ip:

affinity:
  label: 
  value:
