# Default values for ups-mon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: abarruda/nut-server
  tag: test
  pullPolicy: IfNotPresent
  api:
    name: abarruda/nut-rest-api
    tag: test

liveness:
  initialDelaySeconds: 60
  periodSeconds: 60

readiness:
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 6
  api:
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 6

config:
  timezone: America/Los_Angeles
  ups:
    name: 
    fullName: 
    location: 

  nut.conf:
    mode: standalone

  ups.conf:
    driver: usbhid-ups
    port: auto
    pollInterval: 15

  upsd.conf:
    listen: "127.0.0.1 3493"
    maxAge: 25

  upsd.users:
    admin:
      name:
      password:
    user:
      name:
      password:

  upsmon.conf:
    notifyCmd: /etc/nut/notifycmd.sh
    deadtime: 25

  api:
    xms: "32m"
    xmx: "48m"

secrets:
  alert:
    emailTo: ""
    emailFrom: ""
    emailFromName: ""

    smtp:
      host: ""
      port: ""
      user: ""
      password: ""

    twilio:
      account: ""
      authToken: ""
      fromNumber: ""
      toNumber: ""

service:
  port: 80
  protocol: TCP
  ip:
  api:
    port: 8080
    protocol: TCP

resources:
  server:
    memory:
      limit: "16Mi"
  api:
    memory:
      limit: "64Mi"

nodeSelector: {}

affinity: {}

tolerations: []

test:
  enabled: false
  mockUpsDevicePath: test/CP1500PFCLCD.dev
