apiVersion: v1
kind: Secret
metadata:
  name: ups-mon-secret
type: Opaque
data:
  # upsd.users.admin.name: {{ (index .Values.config "upsd.users").admin.name }}
  # upsd.users.admin.password: {{ (index .Values.config "upsd.users").admin.password }}
