apiVersion: v1
kind: Secret
metadata:
  name: ups-mon-secret
type: Opaque
data:
  ALERT_EMAIL_TO: {{ .Values.secrets.alert.emailTo | b64enc }}
  ALERT_EMAIL_FROM: {{ .Values.secrets.alert.emailFrom | b64enc }}
  ALERT_EMAIL_FROM_NAME: {{ .Values.secrets.alert.emailFromName | b64enc }}
  SMTP_HOST: {{ .Values.secrets.alert.smtp.host | b64enc }}
  SMTP_PORT: "{{ .Values.secrets.alert.smtp.port | b64enc }}"
  SMTP_USER: {{ .Values.secrets.alert.smtp.user | b64enc }}
  SMTP_PASS: {{ .Values.secrets.alert.smtp.password | b64enc }}
  TWILIO_ACCOUNT: {{ .Values.secrets.alert.twilio.account | b64enc }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.alert.twilio.authToken | b64enc }}
  TWILIO_FROM_NUMBER: {{ .Values.secrets.alert.twilio.fromNumber | b64enc }}
  TWILIO_TO_NUMBER: {{ .Values.secrets.alert.twilio.toNumber | b64enc }}
