apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}

spec:
  selector:
    app: {{ .Chart.Name }}
  externalTrafficPolicy: Local
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.ip }}

  ports:
  - name: ui-http
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: ui-http
  