FROM arm32v7/debian:9.11-slim

RUN apt-get update && apt-get install -y \
	nut \
	nut-client \
	nut-server \
	nut-cgi \
	nginx \ 
	fcgiwrap \
	msmtp \
	curl

RUN echo "I_HAVE_SECURED_MY_CGI_DIRECTORY" >> /etc/nut/upsset.conf 

EXPOSE 80

COPY entrypoint.sh /entrypoint.sh

HEALTHCHECK CMD upsc CyberPower-1400VA@localhost

ENTRYPOINT /entrypoint.sh